databases:
  - name: knowledge-platform-db
    plan: free

services:
  # The Spring Boot Backend
  - type: web
    name: knowledge-platform-backend
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: knowledge-platform-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: knowledge-platform-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: knowledge-platform-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: knowledge-platform-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: knowledge-platform-db
          property: password
