databases:
  - name: knowledge-platform-db
    plan: free

services:
  # The Spring Boot Backend
  - type: web
    name: knowledge-platform-backend
    env: docker
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: knowledge-platform-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: knowledge-platform-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: knowledge-platform-db
          property: password
